# Generated by Django 5.2.7 on 2026-05-04 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_logo', models.ImageField(upload_to='auction_logos/')),
                ('auction_name', models.CharField(max_length=200)),
                ('auction_date', models.DateField()),
                ('points_per_team', models.IntegerField()),
                ('minimum_bid', models.IntegerField()),
                ('bid_increase_by', models.IntegerField()),
                ('players_per_team', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
