# Generated by Django 5.2.7 on 2026-05-04 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_image', models.ImageField(upload_to='players/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RHB', 'Right Hand Batsman'), ('LHB', 'Left Hand Batsman'), ('RHB_AR', 'Right Hand All-Rounder'), ('LHB_AR', 'Left Hand All-Rounder'), ('BOWLER', 'Bowler'), ('WICKET_KEEPER', 'Wicket Keeper')], max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField()),
                ('tshirt_size', models.CharField(max_length=20)),
                ('trouser_size', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
