# Generated by Django 5.2.7 on 2026-05-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('RHB', 'Right Hand Batsman'), ('LHB', 'Left Hand Batsman'), ('RHB_AR', 'Right Hand All-Rounder'), ('LHB_AR', 'Left Hand All-Rounder'), ('RBOWLER', 'Right Arm Bowler'), ('LBOWLER', 'Left Arm Bowler'), ('WICKET_KEEPER', 'Wicket Keeper')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
