# Generated by Django 5.2.7 on 2026-05-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.auction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
    ]
