# Generated by Django 5.2.7 on 2026-05-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_player_base_price_player_sold_price_player_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='total_spent',
        ),
        migrations.AddField(
            model_name='team',
            name='remaining_points',
            field=models.IntegerField(default=0),
        ),
    ]
